### ISSUE TITLE
Why not merge your Steam repo with RPM Fusion?

### ISSUE THREAD

**Issue by audreytoskin** [negativo17/steam#1]
You maintain your [personal steam repo](http://negativo17.org/steam/), and the Steam packages on RPM Fusion. Right? These are both you?

Why not merge your repo with the packages on RPM Fusion? Seems like it would be less work for you to maintain only a single version of all the packages, and easier for the user to have one less repository to refresh. This seems like such an obvious solution to me, that I would guess you have your reasons for not doing it, but I couldn't find anything on your blog about why you keep the Negativo17 Steam repo separate from the RPM Fusion packages.

**Comment by scaronni** [comment]
Hello, question is good, there are a few reasons:

1- I've been asked by Red Hat not to provide the option to avoid using the Ubuntu Runtime by default, which in turn was asked to them by Valve. Since the steam package here carries that variant with a different set of patches I can't just make an "add on" to the RPMFusion package. I've also added to the Valve wiki the default being RPMFusion and "optional" this repository.

2- I'm providing the replacement xpad kernel module, and this can't be included in Fedora/RPMFusion for policy reasons; you can not overwrite a kernel module provided by the kernel, you need to make your patch approved upstream first.

3- I don't really see the benefit of having the steamos packages everywhere, they're more for a niche set of tinkerers.

Regards,
--Simone

**Comment by audreytoskin** [comment]
Alright, fair enough. Thanks for all the work you put in.
